# Generated by Django 4.1.3 on 2022-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(
                    max_length=255,
                    verbose_name='Имя')),
            ],
        ),
    ]
