# Generated by Django 4.1.3 on 2022-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelForTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=255,
                                          verbose_name='Имя')),
                ('description',
                 models.TextField(null=True,
                                  verbose_name='Описание')),
                ('time_create',
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name='Дата создания')),
            ],
        ),
    ]
