# Generated by Django 4.1.3 on 2022-11-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelfortask',
            old_name='label',
            new_name='labels',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='label',
            new_name='labels',
        ),
    ]
